package:
  name: python-keystoneclient
  version: "1.6.0"

source:
  fn: python-keystoneclient-1.6.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-keystoneclient/python-keystoneclient-1.6.0.tar.gz
  md5: 7c75a78389644433f2346930ba3a3e2a
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - keystone = keystoneclient.shell:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr >=0.11,<2.0

  run:
    - python
    - argparse # [py26]
    - babel >=1.3
    - iso8601 >=0.1.9
    - netaddr >=0.7.12
    - oslo.config >=1.11.0
    - oslo.i18n >=1.5.0
    - oslo.serialization >=1.4.0
    - oslo.utils >=1.4.0
    - prettytable >=0.7,<0.8
    - requests >=2.5.2
    - six >=1.9.0
    - stevedore >=1.3.0

test:
  imports:
    - keystoneclient.client

  commands:
    - keystone --version

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'Client Library for OpenStack Identity'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
